/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    MovieList: typeof import('./src/components/MovieList.vue')['default']
    MovieType: typeof import('./src/components/MovieType.vue')['default']
    PageNation: typeof import('./src/components/PageNation.vue')['default']
    PagiNation: typeof import('./src/components/PagiNation.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
